- name: configure webserver
  hosts: all
  tasks:
  - name: create user
    user:
     name: jampel
     state: present
  - name: install package
    yum:
     name: httpd
     state: present
  - name: create file
    copy:
     content: "Hello Ansible with Jenkins"
     dest: /var/www/html/index.html
  - name: restart service
    service:
     name: httpd
     state: restarted
     enabled: yes
